RelativeLayout:
    padding: 10

    # Back button
    Button:
        id: back_btn_layout
        size_hint: None, None
        size: 50, 50
        pos_hint: {"x": 0, "top": 1}  # linksboven
        background_color: 0, 0, 0, 0
        background_normal: "assets/back_button.png"
        on_release: app.on_exit_btn()
        Image:
            source: "assets/back_button_normal.png" if self.parent.state == "normal" else "assets/back_button_down.png"
            size: self.parent.size
            pos: self.parent.pos

    # Label naast de back button
    Label:
        id: counter_label
        text: "Tic: 0"
        font_size: 40
        size_hint: None, None
        size: self.texture_size
        pos_hint: {"x": 0.15, "top": 0.95}

    # Camera widget in het midden
    CameraWidget:
        id: camera0
        size_hint: 0.5, 0.5
        pos_hint: {"center_x": 0.5, "y": 0.05}  # vrij te positioneren

