BoxLayout:
    orientation: 'vertical'
    padding: 10
    spacing: 10

    # Top bar met back button en label
    BoxLayout:
        size_hint_y: None
        size_hint: 0.1
        spacing: 10

        Button:
            id: back_btn_layout
            size_hint_x: None
            width: 50
            background_color: 0, 0, 0, 0
            background_normal: "assets/back_button.png"
            on_release: app.on_exit_btn()
            Image:
                source: "assets/back_button_normal.png" if self.parent.state == "normal" else "assets/back_button_down.png"
                size: self.parent.size
                pos: self.parent.pos

        Label:
            id: counter_label
            text: "Tic: 0"
            font_size: 40
            valign: "middle"
            halign: "left"
            text_size: self.size

    # Camera widget in het midden
    CameraWidget:
        id: camera0
        size_hint_y: 0.9
