BoxLayout:
    orientation: "vertical"

    BoxLayout:
        size_hint_y: None
        height: 50
        spacing: 5
        padding: 5

        Button:
            id: back_btn_layout
            background_normal: "assets/back_button.png"
            on_release: app.on_exit_btn()
            Image:
                source: "assets/back_button_normal.png" if self.parent.state == "normal" else "assets/back_button_down.png"
                size: self.parent.size
                pos: self.parent.pos

        Button:
            text: "Home"
            on_release: screen_manager.current = "home"
        Button:
            text: "Filter"
            on_release: screen_manager.current = "filter"

    # ScreenManager
    ScreenManager:
        id: screen_manager

        HomeScreen:
            name: "home"
        FilterScreen:
            name: "filter"

