<FilterScreen>:
    BoxLayout:
        orientation: "horizontal"
        spacing: 20
        padding: 20

        BoxLayout:
            orientation: "vertical"
            Image:
                id: oak0
            Image
                id: oak1


        BoxLayout:
            orientation: "vertical"
            spacing: 20
            padding: 20

            Label:
                text: "upper_hue"

            Slider:
                slider_id: 'upper_hue'
                min: 0
                max: 255
                value: root.upper_hue
                on_value: root.on_slider_change(self)

            Label:
                text: "lower_hue"

            Slider:
                slider_id: 'lower_hue'
                min: 0
                max: 255
                value: root.lower_hue
                on_value: root.on_slider_change(self)

            Label:
                text: "upper_sat"

            Slider:
                slider_id: 'upper_sat'
                min: 0
                max: 255
                value: root.upper_sat
                on_value: root.on_slider_change(self)

            Label:
                text: "lower_sat"

            Slider:
                slider_id: 'lower_sat'
                min: 0
                max: 255
                value: root.lower_sat
                on_value: root.on_slider_change(self)

            Label:
                text: "upper_val"

            Slider:
                slider_id: 'upper_val'
                min: 0
                max: 255
                value: root.upper_val
                on_value: root.on_slider_change(self)

            Label:
                text: "lower_val"

            Slider:
                slider_id: 'lower_val'
                min: 0
                max: 255
                value: root.lower_val
                on_value: root.on_slider_change(self)

            TextInput:
                multiline: False
                input_filter: 'int'
                hint_text: 'minimal detection area'
                on_text_validate: root.set_detection_radius(self.text)

            TextInput:
                multiline: False
                input_filter: 'int'
                hint_text: 'amount of water to give'
                on_text_validate: root.set_amount_of_water(self.text)